# Notebook 1 – Data crawling & acquisition

In this notebook, we build the **data acquisition** stage of the movie knowledge graph pipeline using **structured web sources** rather than hardcoded sample data. We query **Wikidata** through its SPARQL endpoint to collect film metadata, then use the **Wikipedia REST API** to retrieve textual summaries for information extraction in later notebooks.

We also check `robots.txt` before making requests, so the crawling process remains aligned with basic web ethics and course expectations.

The outputs of this notebook will be saved for the next stages of the project:
- `data/raw/wikidata_films.json` for structured movie metadata
- `data/raw/wiki_plots.jsonl` for textual summaries

> **Note:** This notebook requires internet access. If you run it in an offline environment, the crawling cells will fail. It is designed to run in **Google Colab** or another notebook environment with network access.

In [1]:
# Cell 1 — Setup, imports, session, and robots.txt note

%pip install -q SPARQLWrapper tqdm

import os
import json
import time
import random
import urllib.robotparser
import requests
import pandas as pd

from urllib.error import HTTPError
from SPARQLWrapper import SPARQLWrapper, JSON
from tqdm.auto import tqdm

os.makedirs("data/raw", exist_ok=True)

HEADERS = {
    "User-Agent": "MoviesKGBot/1.0 (university project; educational use)"
}

session = requests.Session()
session.headers.update(HEADERS)

# Read robots.txt files
rp_wikidata = urllib.robotparser.RobotFileParser()
rp_wikidata.set_url("https://www.wikidata.org/robots.txt")
rp_wikidata.read()

rp_wikipedia = urllib.robotparser.RobotFileParser()
rp_wikipedia.set_url("https://en.wikipedia.org/robots.txt")
rp_wikipedia.read()

print("robots.txt fetched for Wikidata and Wikipedia.")
print("Note: robotparser may report False for these endpoints.")
print("In this notebook, we still use small batches, explicit User-Agent headers, and delays between requests.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.4/615.4 kB 9.8 MB/s eta 0:00:00
robots.txt fetched for Wikidata and Wikipedia.
Note: robotparser may report False for these endpoints.
In this notebook, we still use small batches, explicit User-Agent headers, and delays between requests.

In [2]:
# Cell 2 — Base crawl from Wikipedia categories + Wikidata QIDs (no SPARQL)

from tqdm.auto import tqdm

TARGET_FILMS = 1000
CATEGORY_TITLES = [
    "Category:2024 films",
    "Category:2023 films",
    "Category:2022 films",
    "Category:2021 films",
    "Category:2020 films",
]

WIKIPEDIA_API = "https://en.wikipedia.org/w/api.php"

def fetch_category_titles(category_title, max_titles=200):
    """
    Fetch page titles from a Wikipedia category using the MediaWiki API.
    """
    titles = []
    cmcontinue = None

    while len(titles) < max_titles:
        params = {
            "action": "query",
            "list": "categorymembers",
            "cmtitle": category_title,
            "cmtype": "page",
            "cmlimit": "max",
            "format": "json",
        }
        if cmcontinue:
            params["cmcontinue"] = cmcontinue

        response = session.get(WIKIPEDIA_API, params=params, timeout=30)
        response.raise_for_status()
        data = response.json()

        members = data.get("query", {}).get("categorymembers", [])
        if not members:
            break

        for member in members:
            title = member["title"]
            # light filtering to avoid obvious non-film pages
            if not title.lower().startswith("list of"):
                titles.append(title)
                if len(titles) >= max_titles:
                    break

        cmcontinue = data.get("continue", {}).get("cmcontinue")
        if not cmcontinue:
            break

        time.sleep(0.5)

    return titles

def fetch_wikibase_ids(titles_batch):
    """
    Map English Wikipedia page titles to Wikidata item IDs using pageprops.
    """
    params = {
        "action": "query",
        "prop": "pageprops",
        "ppprop": "wikibase_item",
        "titles": "|".join(titles_batch),
        "format": "json",
    }

    response = session.get(WIKIPEDIA_API, params=params, timeout=30)
    response.raise_for_status()
    data = response.json()

    results = []
    pages = data.get("query", {}).get("pages", {})
    for _, page in pages.items():
        title = page.get("title")
        qid = page.get("pageprops", {}).get("wikibase_item")
        if title and qid:
            results.append({
                "title": title,
                "qid": qid,
                "uri": f"http://www.wikidata.org/entity/{qid}",
            })
    return results

# Step 1: collect candidate titles from categories
all_titles = []
seen_titles = set()

for category_title in CATEGORY_TITLES:
    print(f"Fetching titles from {category_title} ...")
    titles = fetch_category_titles(category_title, max_titles=TARGET_FILMS)

    for title in titles:
        if title not in seen_titles:
            seen_titles.add(title)
            all_titles.append(title)

    print(f"Collected so far: {len(all_titles)} unique titles")

    if len(all_titles) >= TARGET_FILMS:
        break

all_titles = all_titles[:TARGET_FILMS]
print(f"\nCollected {len(all_titles)} candidate Wikipedia film pages.")

# Step 2: resolve titles to Wikidata IDs in batches
films = []
batch_size = 50

for i in tqdm(range(0, len(all_titles), batch_size), desc="Resolving Wikipedia titles to Wikidata IDs"):
    batch = all_titles[i:i + batch_size]
    batch_results = fetch_wikibase_ids(batch)

    for item in batch_results:
        films.append({
            "uri": item["uri"],
            "id": item["qid"],
            "label": item["title"],
            "wikipedia_title": item["title"],
            "date": None,   # fill later during enrichment
        })

    time.sleep(0.5)

films_df = pd.DataFrame(films).drop_duplicates(subset=["id"]).reset_index(drop=True)

print(f"\nRetrieved {len(films_df)} films with Wikidata IDs.")
display(films_df.head())

Fetching titles from Category:2024 films ...
Collected so far: 1000 unique titles

Collected 1000 candidate Wikipedia film pages.

Resolving Wikipedia titles to Wikidata IDs:   0%|          | 0/20 [00:00<?, ?it/s]

Retrieved 998 films with Wikidata IDs.

,uri,id,label,wikipedia_title,date
0,http://www.wikidata.org/entity/Q138793787,Q138793787,"1+1+1 Life, Love, Chaos","1+1+1 Life, Love, Chaos",None
1,http://www.wikidata.org/entity/Q134083298,Q134083298,1-800-On-Her-Own,1-800-On-Her-Own,None
2,http://www.wikidata.org/entity/Q131929176,Q131929176,100 Litres of Gold,100 Litres of Gold,None
3,http://www.wikidata.org/entity/Q124414981,Q124414981,105 Minuttess,105 Minuttess,None
4,http://www.wikidata.org/entity/Q125081677,Q125081677,10 Lives,10 Lives,None

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [3]:
# Cell 3 — Enrich each film with structured metadata from Wikidata EntityData (no SPARQL)

from tqdm.auto import tqdm

WIKIDATA_API = "https://www.wikidata.org/w/api.php"
label_cache = {}

PROPERTY_MAP = {
    "P57": "directors",
    "P136": "genres",
    "P495": "countries",
    "P345": "imdb_ids",
    "P161": "cast",
    "P166": "awards",
    "P272": "production_companies",
    "P156": "followed_by",
    "P155": "preceded_by",
}

ENTITY_PROPERTIES = {"P57", "P136", "P495", "P161", "P166", "P272", "P156", "P155"}
STRING_PROPERTIES = {"P345"}

def fetch_entity_data(qid, max_retries=4, base_sleep=2):
    """
    Fetch raw Wikidata JSON for one entity via Special:EntityData.
    """
    url = f"https://www.wikidata.org/wiki/Special:EntityData/{qid}.json"

    for attempt in range(max_retries):
        try:
            response = session.get(url, timeout=30)
            response.raise_for_status()
            return response.json()

        except requests.exceptions.RequestException as e:
            if attempt < max_retries - 1:
                wait = base_sleep * (2 ** attempt) + random.uniform(0, 1)
                print(f"EntityData error for {qid}: {e}. Retrying in {wait:.1f}s...")
                time.sleep(wait)
            else:
                print(f"Failed to fetch EntityData for {qid}: {e}")
                return None

def resolve_entity_labels(entity_ids, batch_size=50, max_retries=4, base_sleep=2):
    """
    Resolve Wikidata QIDs to English labels using wbgetentities.
    Uses a cache to avoid repeated API calls.
    """
    unresolved = [eid for eid in entity_ids if eid not in label_cache]

    for start in range(0, len(unresolved), batch_size):
        batch = unresolved[start:start + batch_size]

        params = {
            "action": "wbgetentities",
            "ids": "|".join(batch),
            "props": "labels",
            "languages": "en",
            "format": "json",
        }

        success = False
        for attempt in range(max_retries):
            try:
                response = session.get(WIKIDATA_API, params=params, timeout=30)
                response.raise_for_status()
                data = response.json()

                for eid, entity_data in data.get("entities", {}).items():
                    label = entity_data.get("labels", {}).get("en", {}).get("value", eid)
                    label_cache[eid] = label

                success = True
                break

            except requests.exceptions.RequestException as e:
                if attempt < max_retries - 1:
                    wait = base_sleep * (2 ** attempt) + random.uniform(0, 1)
                    print(f"Label resolution error for batch starting at {start}: {e}. Retrying in {wait:.1f}s...")
                    time.sleep(wait)
                else:
                    print(f"Failed label resolution for batch: {batch}")
                    for eid in batch:
                        label_cache.setdefault(eid, eid)

        if not success:
            for eid in batch:
                label_cache.setdefault(eid, eid)

    return {eid: label_cache.get(eid, eid) for eid in entity_ids}

def extract_claim_values(entity_json, qid):
    """
    Extract relevant property values from a Wikidata EntityData JSON record.
    """
    details = {
        "directors": [],
        "genres": [],
        "countries": [],
        "imdb_ids": [],
        "cast": [],
        "awards": [],
        "production_companies": [],
        "followed_by": [],
        "preceded_by": [],
    }

    if not entity_json:
        return details

    entity = entity_json.get("entities", {}).get(qid, {})
    claims = entity.get("claims", {})

    entity_ids_to_resolve = set()
    raw_entity_values = {field: [] for field in details.keys() if field != "imdb_ids"}

    for prop, output_field in PROPERTY_MAP.items():
        for claim in claims.get(prop, []):
            mainsnak = claim.get("mainsnak", {})
            datavalue = mainsnak.get("datavalue")

            if not datavalue:
                continue

            value = datavalue.get("value")

            if prop in ENTITY_PROPERTIES:
                if isinstance(value, dict) and value.get("entity-type") == "item":
                    entity_id = value.get("id")
                    if entity_id:
                        raw_entity_values[output_field].append(entity_id)
                        entity_ids_to_resolve.add(entity_id)

            elif prop in STRING_PROPERTIES:
                if isinstance(value, str):
                    details[output_field].append(value)

    # Resolve labels for all linked entity IDs in one shot
    id_to_label = resolve_entity_labels(sorted(entity_ids_to_resolve))

    for field, ids in raw_entity_values.items():
        details[field] = sorted({id_to_label.get(eid, eid) for eid in ids})

    details["imdb_ids"] = sorted(set(details["imdb_ids"]))

    return details

# Enrich all films
for film in tqdm(films, desc="Enriching films from Wikidata"):
    qid = film["id"]
    entity_json = fetch_entity_data(qid)
    details = extract_claim_values(entity_json, qid)
    film.update(details)
    time.sleep(0.8)

films_df = pd.DataFrame(films)

print("Enrichment complete.")
display(films_df.head())

Enriching films from Wikidata:   0%|          | 0/998 [00:00<?, ?it/s]

Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q10986502%7CQ12179122%7CQ12228551%7CQ1438531%7CQ22930844%7CQ4166668%7CQ60575798&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1189470%7CQ236839%7CQ2843189%7CQ43092840%7CQ4488&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q134930861%7CQ15731400%7CQ49319%7CQ497759%7CQ505476%7CQ518774%7CQ712860%7CQ8298&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q3194810%7CQ62591332%7CQ6378956%7CQ705446&props=labels&languages=en&format=json. Retrying in 3.0s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q123174%7CQ17190262%7CQ17305144%7CQ183542%7CQ186941%7CQ19587511%7CQ2394970%7CQ2678111%7CQ295974%7CQ299421%7CQ32540222%7CQ3443583%7CQ350601%7CQ40096%7CQ4502477%7CQ4984974%7CQ80805%7CQ822314%7CQ982558&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q3497879&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q114051817&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q10297782%7CQ1482555%7CQ5042824&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q125577239&props=labels&languages=en&format=json. Retrying in 2.3s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q30114466%7CQ494987%7CQ625588%7CQ6678598&props=labels&languages=en&format=json. Retrying in 2.3s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q101797%7CQ130251776%7CQ138005%7CQ17335713%7CQ188772%7CQ21738166%7CQ22278557%7CQ26806%7CQ28252%7CQ2844572%7CQ316596%7CQ320384%7CQ352021%7CQ53094%7CQ56008%7CQ81819%7CQ981821&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q104762283%7CQ64975451&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q6067444%7CQ739%7CQ804%7CQ87074395&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q112152319%7CQ129682732%7CQ235302%7CQ313705%7CQ47537514%7CQ508404%7CQ50874821%7CQ54916227%7CQ779151&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q5315321&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q5084977&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q109629396%7CQ231004%7CQ737183&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q106269461%7CQ123339903%7CQ46737491&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q110898302%7CQ20018321%7CQ5483700&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q109045442%7CQ130375533%7CQ5422590&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q109805561%7CQ136410927%7CQ16136752%7CQ16202034%7CQ16239379%7CQ26706840%7CQ7245969%7CQ7280194&props=labels&languages=en&format=json. Retrying in 2.0s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q5099316&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q2262125&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q311169%7CQ3484203%7CQ348755%7CQ48720232&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q134930961%7CQ21480607%7CQ3195765%7CQ5956218&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q126393091%7CQ28549801%7CQ483771%7CQ664%7CQ7015366&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q18938%7CQ220396%7CQ230782%7CQ24895237%7CQ28599261%7CQ44362%7CQ6197242%7CQ65029898&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1379404&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q122052322%7CQ133815044%7CQ259816%7CQ292107%7CQ313671%7CQ5111829%7CQ6070740%7CQ693730%7CQ7153132&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q193555%7CQ310937%7CQ372311%7CQ41396%7CQ56223982%7CQ77041021&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q104530094%7CQ109664672%7CQ130909639%7CQ132797974%7CQ3046343%7CQ3679866%7CQ3694222&props=labels&languages=en&format=json. Retrying in 2.3s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q484572&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1360916%7CQ18705142%7CQ616960&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q134930825%7CQ134930964&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q133575784&props=labels&languages=en&format=json. Retrying in 2.0s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q104097073&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q100988340%7CQ10873941%7CQ109227464%7CQ118118024%7CQ15727919%7CQ16766%7CQ17362624%7CQ24836385%7CQ29520%7CQ30942475%7CQ55718427%7CQ58182303%7CQ6652453%7CQ6829249%7CQ712121%7CQ712178%7CQ716027%7CQ717579%7CQ718036%7CQ7243087%7CQ846544%7CQ9343509&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q185421%7CQ374065%7CQ39829%7CQ42293003%7CQ467484&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q4798067&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q27656966&props=labels&languages=en&format=json. Retrying in 2.3s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1319539%7CQ210120%7CQ224026%7CQ451934%7CQ6223403%7CQ782662&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q3312968&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q107549328%7CQ110272798%7CQ1138674%7CQ19665276%7CQ1985488%7CQ20993783%7CQ2267853%7CQ23691927%7CQ465406%7CQ542634%7CQ67983845%7CQ76478%7CQ88834138%7CQ90154157%7CQ922503%7CQ96741403&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q145422&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q114903844%7CQ5852528%7CQ8192289&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q111586105%7CQ18698425%7CQ26710710%7CQ29832591%7CQ4661797%7CQ926420&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q6881132&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q106904495%7CQ16233540%7CQ184885%7CQ4849846%7CQ6366618&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q114908293%7CQ20968381%7CQ21154186%7CQ2888100%7CQ5822281%7CQ772729&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q212&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q126363017&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q244234%7CQ2933352%7CQ3476723%7CQ44467%7CQ590103&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q229766%7CQ232120%7CQ25936414%7CQ272972%7CQ2985242%7CQ310932%7CQ461315%7CQ72049754%7CQ794912%7CQ96031382&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q27662543%7CQ7462919%7CQ7560758&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q127694912%7CQ3765029&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q133004804%7CQ484360%7CQ493864%7CQ777387&props=labels&languages=en&format=json. Retrying in 3.0s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q111738586%7CQ124719081%7CQ2040329%7CQ21621919%7CQ47100%7CQ51841920%7CQ6382703%7CQ888535&props=labels&languages=en&format=json. Retrying in 2.2s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q105092616%7CQ115969746%7CQ117317499%7CQ122949690%7CQ189%7CQ25999316%7CQ3180025%7CQ3485101%7CQ68366702%7CQ826043%7CQ971177&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q106175%7CQ22774261%7CQ277193%7CQ703779%7CQ717442%7CQ9079290&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q111356252%7CQ123235745%7CQ17013906%7CQ18638591%7CQ24006918%7CQ3541497%7CQ4802047%7CQ5006286%7CQ61700036%7CQ66309904&props=labels&languages=en&format=json. Retrying in 2.9s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q6365637&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1054807%7CQ64784608&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q31176164%7CQ82692797&props=labels&languages=en&format=json. Retrying in 2.8s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q100156267%7CQ1041563%7CQ1055916%7CQ1058161%7CQ1144984%7CQ13473609%7CQ135455191%7CQ1889868%7CQ269762%7CQ2939659%7CQ3769056%7CQ3836804%7CQ3857845%7CQ3893598%7CQ4007900%7CQ4008556%7CQ4013682%7CQ437502%7CQ451125%7CQ457841%7CQ55460%7CQ63522079%7CQ697471%7CQ707439%7CQ79446673&props=labels&languages=en&format=json. Retrying in 2.5s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q123436285%7CQ18643399%7CQ18643400%7CQ6359085%7CQ6359242%7CQ88307&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q206890%7CQ65116099%7CQ918616&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q131731484%7CQ131762402%7CQ15224941%7CQ16298722%7CQ2602857%7CQ285022&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q109358232%7CQ147395%7CQ15724091%7CQ4967985%7CQ6894206%7CQ7237298%7CQ7461590%7CQ7683939%7CQ7937588%7CQ86531778&props=labels&languages=en&format=json. Retrying in 2.1s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q258%7CQ260622&props=labels&languages=en&format=json. Retrying in 2.4s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q16928132%7CQ20020372%7CQ5696776%7CQ66305673&props=labels&languages=en&format=json. Retrying in 2.6s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q1202502%7CQ13595531%7CQ14752155%7CQ17380672%7CQ175535%7CQ2060840%7CQ20973709%7CQ27974003%7CQ3639959%7CQ5147723%7CQ51769012%7CQ628165%7CQ665532&props=labels&languages=en&format=json. Retrying in 2.7s...
Label resolution error for batch starting at 0: 429 Client Error: Too many requests (f061ab2) for url: https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q123020760&props=labels&languages=en&format=json. Retrying in 2.2s...

,uri,id,label,wikipedia_title,date,directors,genres,countries,imdb_ids,cast,awards,production_companies,followed_by,preceded_by
0,http://www.wikidata.org/entity/Q138793787,Q138793787,"1+1+1 Life, Love, Chaos","1+1+1 Life, Love, Chaos",None,[],[],[],[],[],[],[],[],[]
1,http://www.wikidata.org/entity/Q134083298,Q134083298,1-800-On-Her-Own,1-800-On-Her-Own,None,[Dana Flor],[],[United States],[tt32147765],[],[],[],[],[]
2,http://www.wikidata.org/entity/Q131929176,Q131929176,100 Litres of Gold,100 Litres of Gold,None,[Teemu Nikki],[comedy film],"[Denmark, Finland, Italy]",[tt33311744],"[Elina Knihtilä, Elmer Bäck, Jakob Öhrman, Jar...",[],[],[],[]
3,http://www.wikidata.org/entity/Q124414981,Q124414981,105 Minuttess,105 Minuttess,None,[],[],[],[tt15290106],[],[],[],[],[]
4,http://www.wikidata.org/entity/Q125081677,Q125081677,10 Lives,10 Lives,None,"[Chris Jenkins, Mark Koetsier]","[animated film, comedy film]","[Canada, France, United Kingdom, United States]",[tt7959138],[],[],[],[],[]

In [4]:
# Cell 4 — Fetch Wikipedia summaries with global cooldown on 429

from urllib.parse import quote
from tqdm.auto import tqdm
import os

session = requests.Session()
session.headers.update({
    "User-Agent": HEADERS["User-Agent"]
})

REQUEST_SLEEP = 2.0
GLOBAL_COOLDOWN_ON_429 = 7.0
CHECKPOINT_EVERY = 40

plots_output_path = "/content/wiki_plots.jsonl"

def fetch_wikipedia_summary(title, max_retries=2, base_sleep=2.0):
    encoded_title = quote(title, safe="")
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{encoded_title}"

    for attempt in range(max_retries):
        try:
            response = session.get(url, timeout=10)

            if response.status_code == 200:
                data = response.json()
                summary = data.get("extract", "").strip()
                page_url = (
                    data.get("content_urls", {})
                        .get("desktop", {})
                        .get("page", "")
                )
                return {
                    "summary": summary,
                    "page_url": page_url,
                    "status": 200,
                }

            if response.status_code == 404:
                return {
                    "summary": "",
                    "page_url": "",
                    "status": 404,
                }

            if response.status_code == 429:
                return {
                    "summary": "",
                    "page_url": "",
                    "status": 429,
                }

            if response.status_code in (500, 502, 503, 504):
                wait = base_sleep * (2 ** attempt) + random.uniform(0, 1)
                print(f"Wikipedia HTTP {response.status_code} for {title}. Retrying in {wait:.1f}s...")
                time.sleep(wait)
                continue

            return {
                "summary": "",
                "page_url": "",
                "status": response.status_code,
            }

        except requests.exceptions.RequestException as e:
            if attempt < max_retries - 1:
                wait = base_sleep * (2 ** attempt) + random.uniform(0, 1)
                print(f"Request error for {title}: {e}. Retrying in {wait:.1f}s...")
                time.sleep(wait)
            else:
                return {
                    "summary": "",
                    "page_url": "",
                    "status": "error",
                }

    return {
        "summary": "",
        "page_url": "",
        "status": "failed",
    }

done_ids = set()
plots = []
missing_titles = []

if os.path.exists(plots_output_path):
    with open(plots_output_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rec = json.loads(line)
                done_ids.add(rec.get("id"))
                plots.append(rec)

print(f"Already fetched summaries for {len(done_ids)} films")

processed_in_this_run = 0

with open(plots_output_path, "a", encoding="utf-8") as f:
    for i, film in enumerate(tqdm(films, desc="Fetching Wikipedia summaries"), start=1):
        if film["id"] in done_ids:
            continue

        title = (film.get("wikipedia_title") or film["label"]).strip()
        print(f"[{i}/{len(films)}] {title}")

        result = fetch_wikipedia_summary(title)

        if result["status"] == 200 and result["summary"]:
            record = {
                "id": film["id"],
                "title": title,
                "wikidata_uri": film["uri"],
                "summary": result["summary"],
                "page_url": result["page_url"],
            }
            plots.append(record)
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            f.flush()
            done_ids.add(film["id"])

        elif result["status"] == 429:
            wait = GLOBAL_COOLDOWN_ON_429 + random.uniform(0, 5)
            print(f"Wikipedia rate limit hit on '{title}'. Global cooldown for {wait:.1f}s...")
            time.sleep(wait)

            # retry once after cooldown
            result = fetch_wikipedia_summary(title, max_retries=1)

            if result["status"] == 200 and result["summary"]:
                record = {
                    "id": film["id"],
                    "title": title,
                    "wikidata_uri": film["uri"],
                    "summary": result["summary"],
                    "page_url": result["page_url"],
                }
                plots.append(record)
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
                f.flush()
                done_ids.add(film["id"])
            else:
                missing_titles.append({
                    "id": film["id"],
                    "title": title,
                    "status": result["status"],
                })

        else:
            missing_titles.append({
                "id": film["id"],
                "title": title,
                "status": result["status"],
            })

        processed_in_this_run += 1
        time.sleep(REQUEST_SLEEP + random.uniform(0, 0.3))

        if processed_in_this_run % CHECKPOINT_EVERY == 0:
            pause = 8 + random.uniform(0, 3)
            print(f"Checkpoint pause for {pause:.1f}s...")
            time.sleep(pause)

plots_df = pd.DataFrame(plots)
missing_df = pd.DataFrame(missing_titles)

print(f"Retrieved {len(plots_df)} plot summaries.")
print(f"Missing or failed in this run: {len(missing_df)}")
display(plots_df.head())

Already fetched summaries for 0 films

Fetching Wikipedia summaries:   0%|          | 0/998 [00:00<?, ?it/s]

[1/998] 1+1+1 Life, Love, Chaos
Wikipedia rate limit hit on '1+1+1 Life, Love, Chaos'. Global cooldown for 7.2s...
[2/998] 1-800-On-Her-Own
Wikipedia rate limit hit on '1-800-On-Her-Own'. Global cooldown for 8.9s...
[3/998] 100 Litres of Gold
Wikipedia rate limit hit on '100 Litres of Gold'. Global cooldown for 9.0s...
[4/998] 105 Minuttess
Wikipedia rate limit hit on '105 Minuttess'. Global cooldown for 8.6s...
[5/998] 10 Lives
Wikipedia rate limit hit on '10 Lives'. Global cooldown for 9.3s...
[6/998] 11 Rebels
Wikipedia rate limit hit on '11 Rebels'. Global cooldown for 7.4s...
[7/998] 12 Gaun
Wikipedia rate limit hit on '12 Gaun'. Global cooldown for 9.4s...
[8/998] 14 (film)
Wikipedia rate limit hit on '14 (film)'. Global cooldown for 10.9s...
[9/998] 18×2 Beyond Youthful Days
Wikipedia rate limit hit on '18×2 Beyond Youthful Days'. Global cooldown for 11.9s...
[10/998] 1957 (film)
Wikipedia rate limit hit on '1957 (film)'. Global cooldown for 8.2s...
[11/998] 1970 Love Story
Wikipedia rate limit hit on '1970 Love Story'. Global cooldown for 10.0s...
[12/998] 1978 (film)
Wikipedia rate limit hit on '1978 (film)'. Global cooldown for 7.2s...
[13/998] 1992 (film)
Wikipedia rate limit hit on '1992 (film)'. Global cooldown for 9.4s...
[14/998] 1995 (film)
Wikipedia rate limit hit on '1995 (film)'. Global cooldown for 8.5s...
[15/998] 200% Wolf
Wikipedia rate limit hit on '200% Wolf'. Global cooldown for 7.9s...
[16/998] 2073 (film)
Wikipedia rate limit hit on '2073 (film)'. Global cooldown for 9.8s...
[17/998] 35 Chinna Katha Kaadu
Wikipedia rate limit hit on '35 Chinna Katha Kaadu'. Global cooldown for 9.2s...
[18/998] 40 Acres (film)
Wikipedia rate limit hit on '40 Acres (film)'. Global cooldown for 10.3s...
[19/998] 50 YouTubers Fight for $1,000,000
Wikipedia rate limit hit on '50 YouTubers Fight for $1,000,000'. Global cooldown for 9.5s...
[20/998] 5D (film)
Wikipedia rate limit hit on '5D (film)'. Global cooldown for 7.3s...
[21/998] 7/G
Wikipedia rate limit hit on '7/G'. Global cooldown for 9.1s...
[22/998] 72 Hours (2024 film)
Wikipedia rate limit hit on '72 Hours (2024 film)'. Global cooldown for 8.3s...
[23/998] 78 Days
Wikipedia rate limit hit on '78 Days'. Global cooldown for 7.8s...
[24/998] 7 Beats per Minute
Wikipedia rate limit hit on '7 Beats per Minute'. Global cooldown for 9.4s...
[25/998] 7 Days, 7 Nights
Wikipedia rate limit hit on '7 Days, 7 Nights'. Global cooldown for 8.8s...
[26/998] 7 Walks with Mark Brown
Wikipedia rate limit hit on '7 Walks with Mark Brown'. Global cooldown for 7.0s...
[27/998] 840 (film)
Wikipedia rate limit hit on '840 (film)'. Global cooldown for 8.7s...
[28/998] 8 Don 75
Wikipedia rate limit hit on '8 Don 75'. Global cooldown for 7.1s...
[29/998] 8 Views of Lake Biwa
Wikipedia rate limit hit on '8 Views of Lake Biwa'. Global cooldown for 10.2s...
[30/998] 9 Windows
Wikipedia rate limit hit on '9 Windows'. Global cooldown for 9.2s...
[31/998] Aa Okkati Adakku (2024 film)
Wikipedia rate limit hit on 'Aa Okkati Adakku (2024 film)'. Global cooldown for 11.2s...
[32/998] Aakhir Palaayan Kab Tak
Wikipedia rate limit hit on 'Aakhir Palaayan Kab Tak'. Global cooldown for 9.6s...
[33/998] Aalakaalam
Wikipedia rate limit hit on 'Aalakaalam'. Global cooldown for 9.5s...
[34/998] Aalan
Wikipedia rate limit hit on 'Aalan'. Global cooldown for 11.2s...
[35/998] Aanandhapuram Diaries
Wikipedia rate limit hit on 'Aanandhapuram Diaries'. Global cooldown for 11.9s...
[36/998] Aaraam Arvind Swamy
Wikipedia rate limit hit on 'Aaraam Arvind Swamy'. Global cooldown for 7.6s...
[37/998] Aaragan
Wikipedia rate limit hit on 'Aaragan'. Global cooldown for 8.4s...
[38/998] Aarambham (2024 film)
Wikipedia rate limit hit on 'Aarambham (2024 film)'. Global cooldown for 9.7s...
[39/998] Aaryamala
Wikipedia rate limit hit on 'Aaryamala'. Global cooldown for 8.9s...
[40/998] Aavesham (2024 film)
Wikipedia rate limit hit on 'Aavesham (2024 film)'. Global cooldown for 11.7s...
Checkpoint pause for 10.7s...
[41/998] Aay (film)
Wikipedia rate limit hit on 'Aay (film)'. Global cooldown for 7.0s...
[42/998] Aayushmati Geeta Matric Pass
Wikipedia rate limit hit on 'Aayushmati Geeta Matric Pass'. Global cooldown for 9.1s...
[43/998] Ababooned
Wikipedia rate limit hit on 'Ababooned'. Global cooldown for 7.6s...
[44/998] Abbabba
Wikipedia rate limit hit on 'Abbabba'. Global cooldown for 8.9s...
[45/998] Abdo & Saneya
Wikipedia rate limit hit on 'Abdo & Saneya'. Global cooldown for 10.3s...
[46/998] Aberdeen (2024 film)
Wikipedia rate limit hit on 'Aberdeen (2024 film)'. Global cooldown for 10.1s...
[47/998] An Abandoned Team
Wikipedia rate limit hit on 'An Abandoned Team'. Global cooldown for 11.2s...
[48/998] The 21
Wikipedia rate limit hit on 'The 21'. Global cooldown for 8.9s...
[49/998] The 47
Wikipedia rate limit hit on 'The 47'. Global cooldown for 7.5s...
[50/998] The 4:30 Movie (film)
Wikipedia rate limit hit on 'The 4:30 Movie (film)'. Global cooldown for 7.8s...
[51/998] Abhi (2024 film)
Wikipedia rate limit hit on 'Abhi (2024 film)'. Global cooldown for 9.5s...
[52/998] Abhirami (2024 film)
Wikipedia rate limit hit on 'Abhirami (2024 film)'. Global cooldown for 9.3s...
[53/998] Abi-e Roshan
Wikipedia rate limit hit on 'Abi-e Roshan'. Global cooldown for 11.0s...
[54/998] Abigail (2024 film)
Wikipedia rate limit hit on 'Abigail (2024 film)'. Global cooldown for 7.1s...
[55/998] About Family
Wikipedia rate limit hit on 'About Family'. Global cooldown for 8.5s...
[56/998] Abraham Ozler
Wikipedia rate limit hit on 'Abraham Ozler'. Global cooldown for 10.2s...
[57/998] Absolution (2024 film)
Wikipedia rate limit hit on 'Absolution (2024 film)'. Global cooldown for 10.2s...
[58/998] Accident or Conspiracy: Godhra
Wikipedia rate limit hit on 'Accident or Conspiracy: Godhra'. Global cooldown for 7.6s...
[59/998] Across the Sea (film)
Wikipedia rate limit hit on 'Across the Sea (film)'. Global cooldown for 11.6s...
[60/998] Adam Sandler: Love You
Wikipedia rate limit hit on 'Adam Sandler: Love You'. Global cooldown for 9.2s...
[61/998] Adam the First
Wikipedia rate limit hit on 'Adam the First'. Global cooldown for 10.9s...
[62/998] Adbhut
Wikipedia rate limit hit on 'Adbhut'. Global cooldown for 11.6s...
[63/998] Ade (On a Sunday)
Wikipedia rate limit hit on 'Ade (On a Sunday)'. Global cooldown for 7.8s...
[64/998] Adharma Kadhaigal
Wikipedia rate limit hit on 'Adharma Kadhaigal'. Global cooldown for 7.2s...
[65/998] Adios Amigo (2024 film)
Wikipedia rate limit hit on 'Adios Amigo (2024 film)'. Global cooldown for 7.5s...
[66/998] Adrianne and the Castle
Wikipedia rate limit hit on 'Adrianne and the Castle'. Global cooldown for 9.4s...
[67/998] Adult Best Friends
Wikipedia rate limit hit on 'Adult Best Friends'. Global cooldown for 11.8s...
[68/998] Adult Swim Yule Log 2: Branchin' Out
Wikipedia rate limit hit on 'Adult Swim Yule Log 2: Branchin' Out'. Global cooldown for 9.5s...
[69/998] Ae Watan Mere Watan
Wikipedia rate limit hit on 'Ae Watan Mere Watan'. Global cooldown for 10.4s...
[70/998] Affections (film)
Wikipedia rate limit hit on 'Affections (film)'. Global cooldown for 7.8s...
[71/998] Afraid (film)
Wikipedia rate limit hit on 'Afraid (film)'. Global cooldown for 12.0s...
[72/998] African Giants
Wikipedia rate limit hit on 'African Giants'. Global cooldown for 10.1s...
[73/998] After Party (film)
Wikipedia rate limit hit on 'After Party (film)'. Global cooldown for 9.4s...
[74/998] After the Odyssey
Wikipedia rate limit hit on 'After the Odyssey'. Global cooldown for 7.7s...
[75/998] After the Silence
Wikipedia rate limit hit on 'After the Silence'. Global cooldown for 9.5s...
[76/998] Aftermath (2024 film)
Wikipedia rate limit hit on 'Aftermath (2024 film)'. Global cooldown for 9.1s...
[77/998] Afternoons of Solitude
Wikipedia rate limit hit on 'Afternoons of Solitude'. Global cooldown for 11.2s...
[78/998] Agak Laen
Wikipedia rate limit hit on 'Agak Laen'. Global cooldown for 9.6s...
[79/998] Agastya: Chapter 1
Wikipedia rate limit hit on 'Agastya: Chapter 1'. Global cooldown for 11.5s...
[80/998] Agent Recon
Wikipedia rate limit hit on 'Agent Recon'. Global cooldown for 10.4s...
Checkpoint pause for 9.7s...
[81/998] Agent of Happiness
Wikipedia rate limit hit on 'Agent of Happiness'. Global cooldown for 8.1s...
[82/998] Agni (2024 film)
Wikipedia rate limit hit on 'Agni (2024 film)'. Global cooldown for 8.9s...
[83/998] Agontuk
Wikipedia rate limit hit on 'Agontuk'. Global cooldown for 10.3s...
[84/998] Aham Reboot
Wikipedia rate limit hit on 'Aham Reboot'. Global cooldown for 10.4s...
[85/998] Aho Vikramaarka
Wikipedia rate limit hit on 'Aho Vikramaarka'. Global cooldown for 11.6s...
[86/998] Air Force One Down
Wikipedia rate limit hit on 'Air Force One Down'. Global cooldown for 10.5s...
[87/998] Aire: Just Breathe
Wikipedia rate limit hit on 'Aire: Just Breathe'. Global cooldown for 10.3s...
[88/998] Ajab Raat Ni Gajab Vaat
[89/998] Ajogyo
Wikipedia rate limit hit on 'Ajogyo'. Global cooldown for 10.7s...
[90/998] Akkaran
Wikipedia rate limit hit on 'Akkaran'. Global cooldown for 8.4s...
[91/998] Alaap (2024 film)
Wikipedia rate limit hit on 'Alaap (2024 film)'. Global cooldown for 11.0s...
[92/998] Alakada: Bad and Boujee
Wikipedia rate limit hit on 'Alakada: Bad and Boujee'. Global cooldown for 7.5s...
[93/998] Alanaati Ramchandrudu
[94/998] Alangu
Wikipedia rate limit hit on 'Alangu'. Global cooldown for 7.1s...
[95/998] Albany Road
Wikipedia rate limit hit on 'Albany Road'. Global cooldown for 9.4s...
[96/998] Alberta Number One
Wikipedia rate limit hit on 'Alberta Number One'. Global cooldown for 11.4s...
[97/998] Alec Guinness: A Class Act
Wikipedia rate limit hit on 'Alec Guinness: A Class Act'. Global cooldown for 9.7s...
[98/998] Aïcha (film)
Wikipedia rate limit hit on 'Aïcha (film)'. Global cooldown for 9.3s...
[99/998] The Adamant Girl
Wikipedia rate limit hit on 'The Adamant Girl'. Global cooldown for 11.9s...
[100/998] The Akaali
Wikipedia rate limit hit on 'The Akaali'. Global cooldown for 11.2s...
[101/998] AMFAD All My Friends Are Dead
Wikipedia rate limit hit on 'AMFAD All My Friends Are Dead'. Global cooldown for 7.6s...
[102/998] Algiers (2024 film)
Wikipedia rate limit hit on 'Algiers (2024 film)'. Global cooldown for 11.7s...
[103/998] Alibaba Aani Chalishitale Chor
Wikipedia rate limit hit on 'Alibaba Aani Chalishitale Chor'. Global cooldown for 10.0s...
[104/998] Alien: Romulus
Wikipedia rate limit hit on 'Alien: Romulus'. Global cooldown for 10.1s...
[105/998] Alienoid: Return to the Future
Wikipedia rate limit hit on 'Alienoid: Return to the Future'. Global cooldown for 11.8s...
[106/998] Alipato at Muog
Wikipedia rate limit hit on 'Alipato at Muog'. Global cooldown for 9.4s...
[107/998] Aliya Basu Gayab Hai
Wikipedia rate limit hit on 'Aliya Basu Gayab Hai'. Global cooldown for 7.7s...
[108/998] All's Fair in Love (2024 film)
Wikipedia rate limit hit on 'All's Fair in Love (2024 film)'. Global cooldown for 10.5s...
[109/998] All Access to Rossa 25 Shining Years
Wikipedia rate limit hit on 'All Access to Rossa 25 Shining Years'. Global cooldown for 7.1s...
[110/998] All Shall Be Well (film)
Wikipedia rate limit hit on 'All Shall Be Well (film)'. Global cooldown for 9.8s...
[111/998] All Stirred Up!
Wikipedia rate limit hit on 'All Stirred Up!'. Global cooldown for 8.8s...
[112/998] All That We Love
Wikipedia rate limit hit on 'All That We Love'. Global cooldown for 11.6s...
[113/998] All We Imagine as Light
Wikipedia rate limit hit on 'All We Imagine as Light'. Global cooldown for 9.1s...
[114/998] All We Need Is Time
Wikipedia rate limit hit on 'All We Need Is Time'. Global cooldown for 7.1s...
[115/998] All for One (2024 film)
Wikipedia rate limit hit on 'All for One (2024 film)'. Global cooldown for 9.1s...
[116/998] All of You (2024 film)
Wikipedia rate limit hit on 'All of You (2024 film)'. Global cooldown for 7.2s...
[117/998] All the Long Nights
Wikipedia rate limit hit on 'All the Long Nights'. Global cooldown for 8.3s...
[118/998] All the Lost Ones
Wikipedia rate limit hit on 'All the Lost Ones'. Global cooldown for 11.7s...
[119/998] Allahr Vres
Wikipedia rate limit hit on 'Allahr Vres'. Global cooldown for 8.1s...
[120/998] Allen Sunshine
Wikipedia rate limit hit on 'Allen Sunshine'. Global cooldown for 7.1s...
Checkpoint pause for 10.9s...
[121/998] Almost Legal
Wikipedia rate limit hit on 'Almost Legal'. Global cooldown for 7.5s...
[122/998] Almost Popular
Wikipedia rate limit hit on 'Almost Popular'. Global cooldown for 9.6s...
[123/998] Alone in the Night (2024 film)
Wikipedia rate limit hit on 'Alone in the Night (2024 film)'. Global cooldown for 10.3s...
[124/998] Alpha.
Wikipedia rate limit hit on 'Alpha.'. Global cooldown for 8.6s...
[125/998] Altered (2024 film)
Wikipedia rate limit hit on 'Altered (2024 film)'. Global cooldown for 10.4s...
[126/998] Altered Reality
Wikipedia rate limit hit on 'Altered Reality'. Global cooldown for 11.1s...
[127/998] Alyad Palyad
Wikipedia rate limit hit on 'Alyad Palyad'. Global cooldown for 11.1s...
[128/998] Am I Racist?
Wikipedia rate limit hit on 'Am I Racist?'. Global cooldown for 7.8s...
[129/998] Amaltash
Wikipedia rate limit hit on 'Amaltash'. Global cooldown for 10.0s...
[130/998] Amar Prem Ki Prem Kahani
Wikipedia rate limit hit on 'Amar Prem Ki Prem Kahani'. Global cooldown for 10.8s...
[131/998] Amar Singh Chamkila (film)
Wikipedia rate limit hit on 'Amar Singh Chamkila (film)'. Global cooldown for 9.0s...
[132/998] Amaran (2024 film)
Wikipedia rate limit hit on 'Amaran (2024 film)'. Global cooldown for 11.2s...
[133/998] Amazon Bullseye
Wikipedia rate limit hit on 'Amazon Bullseye'. Global cooldown for 7.4s...
[134/998] Ambajipeta Marriage Band
Wikipedia rate limit hit on 'Ambajipeta Marriage Band'. Global cooldown for 7.9s...
[135/998] Amber Alert (film)
Wikipedia rate limit hit on 'Amber Alert (film)'. Global cooldown for 8.8s...
[136/998] Ameena (film)
Wikipedia rate limit hit on 'Ameena (film)'. Global cooldown for 11.1s...
[137/998] America's Burning
Wikipedia rate limit hit on 'America's Burning'. Global cooldown for 10.9s...
[138/998] American MILF
Wikipedia rate limit hit on 'American MILF'. Global cooldown for 7.8s...
[139/998] American Star (film)
Wikipedia rate limit hit on 'American Star (film)'. Global cooldown for 9.9s...
[140/998] Amigo Garage
Wikipedia rate limit hit on 'Amigo Garage'. Global cooldown for 8.4s...
[141/998] Among Mountains and Streams
Wikipedia rate limit hit on 'Among Mountains and Streams'. Global cooldown for 11.2s...
[142/998] Amongst the Wolves
Wikipedia rate limit hit on 'Amongst the Wolves'. Global cooldown for 8.8s...
[143/998] An Almost Christmas Story
Wikipedia rate limit hit on 'An Almost Christmas Story'. Global cooldown for 8.4s...
[144/998] An Taibhse
Wikipedia rate limit hit on 'An Taibhse'. Global cooldown for 7.5s...
[145/998] Anak Kolong
Wikipedia rate limit hit on 'Anak Kolong'. Global cooldown for 11.3s...
[146/998] Anand Sreebala
Wikipedia rate limit hit on 'Anand Sreebala'. Global cooldown for 9.8s...
[147/998] Anathema (film)
Wikipedia rate limit hit on 'Anathema (film)'. Global cooldown for 10.9s...
[148/998] Anchakkallakokkan
Wikipedia rate limit hit on 'Anchakkallakokkan'. Global cooldown for 10.1s...
[149/998] The American Backyard
Wikipedia rate limit hit on 'The American Backyard'. Global cooldown for 10.0s...
[150/998] The American Society of Magical Negroes
Wikipedia rate limit hit on 'The American Society of Magical Negroes'. Global cooldown for 12.0s...
[151/998] ARM (film)
Wikipedia rate limit hit on 'ARM (film)'. Global cooldown for 7.0s...
[152/998] An Army of Women
Wikipedia rate limit hit on 'An Army of Women'. Global cooldown for 7.6s...
[153/998] And Mrs
Wikipedia rate limit hit on 'And Mrs'. Global cooldown for 7.2s...
[154/998] And So It Begins (film)
Wikipedia rate limit hit on 'And So It Begins (film)'. Global cooldown for 8.2s...
[155/998] And Their Children After Them (film)
Wikipedia rate limit hit on 'And Their Children After Them (film)'. Global cooldown for 8.5s...
[156/998] And the Breadwinner Is...
Wikipedia rate limit hit on 'And the Breadwinner Is...'. Global cooldown for 7.3s...
[157/998] Andhagan
Wikipedia rate limit hit on 'Andhagan'. Global cooldown for 7.0s...
[158/998] Andrea Gets a Divorce
Wikipedia rate limit hit on 'Andrea Gets a Divorce'. Global cooldown for 7.4s...
[159/998] Angammal
[160/998] Angela's Shadow
Wikipedia rate limit hit on 'Angela's Shadow'. Global cooldown for 11.7s...
Checkpoint pause for 11.0s...
[161/998] Angels Fallen: Warriors of Peace
Wikipedia rate limit hit on 'Angels Fallen: Warriors of Peace'. Global cooldown for 11.4s...
[162/998] Animalia Paradoxa (film)
Wikipedia rate limit hit on 'Animalia Paradoxa (film)'. Global cooldown for 8.5s...
[163/998] Anjaamai
Wikipedia rate limit hit on 'Anjaamai'. Global cooldown for 7.2s...
[164/998] Anora
[165/998] Another End
Wikipedia rate limit hit on 'Another End'. Global cooldown for 11.7s...
[166/998] Another Summer Holiday
Wikipedia rate limit hit on 'Another Summer Holiday'. Global cooldown for 11.4s...
[167/998] Anpanman: Baikinman and Lulun in the Picture Book
Wikipedia rate limit hit on 'Anpanman: Baikinman and Lulun in the Picture Book'. Global cooldown for 11.6s...
[168/998] Antidote (2024 film)
Wikipedia rate limit hit on 'Antidote (2024 film)'. Global cooldown for 10.2s...
[169/998] Antima Theerpu (2024 film)
Wikipedia rate limit hit on 'Antima Theerpu (2024 film)'. Global cooldown for 10.1s...
[170/998] Anuja (film)
Wikipedia rate limit hit on 'Anuja (film)'. Global cooldown for 7.9s...
[171/998] Anweshippin Kandethum
[172/998] Any Day Now (2024 film)
[173/998] Any Other Way: The Jackie Shane Story
[174/998] Anywhere Anytime
[175/998] Apartment 7A
[176/998] Apocalypse Z: The Beginning of the End
[177/998] Apocalypse in the Tropics
[178/998] Appa I Love You
[179/998] Appudo Ippudo Eppudo
[180/998] April (2024 film)
[181/998] Aranam
[182/998] Aranmanai 4
[183/998] Arcadia (2024 film)
[184/998] Arcadian (film)
[185/998] Architecton
[186/998] Are You Scared to Be Yourself Because You Think That You Might Fail?
[187/998] Arena Wars (film)
[188/998] Argylle
[189/998] Ari's Theme
[190/998] Arimapatti Sakthivel
[191/998] Arjun Chakravarthy
[192/998] Armand (film)
[193/998] Armor (film)
[194/998] Art of Love (2024 film)
[195/998] The Antique (2024 film)
[196/998] The Antisocial Network (film)
[197/998] The Apprentice (2024 film)
[198/998] The Architecture of Love
[199/998] The Art of Healing Descendant Pain
[200/998] Art Spiegelman: Disaster Is My Muse
Checkpoint pause for 8.9s...
[201/998] Arthur's Whisky
[202/998] Arthur the King
[203/998] Article 20
[204/998] Article 370 (film)
[205/998] Artificial Justice
[206/998] Arzé
[207/998] As Neves (film)
[208/998] As Silence Passes By
[209/998] Aserb: The Squadron
[210/998] Ask Me What You Want
[211/998] At All Kosts
[212/998] At Averroès & Rosa Parks
[213/998] Atatürk (film)
[214/998] Athhoi
[215/998] Athomugam
[216/998] Atlas (2024 film)
[217/998] Audrey's Children
[218/998] Audrey (2024 film)
[219/998] Auron Mein Kahan Dum Tha
[220/998] Autumn and the Black Jaguar
[221/998] Avatara Purusha 2
[222/998] Average Student Nani
[223/998] Avicii – I'm Tim
[224/998] Ayalaan
[225/998] Azrael (film)
[226/998] Babai Ghahraman
[227/998] Babes (film)
[228/998] Babies Don't Come with Instructions
[229/998] Babli (film)
[230/998] Baby (2024 film)
[231/998] Baby Assassins: Nice Days
[232/998] Baby Invasion
[233/998] Baby John (film)
[234/998] Babygirl
[235/998] Bachchala Malli
[236/998] Bachelor Party (2024 film)
[237/998] Back Bencherz
[238/998] Back to Black (film)
[239/998] Bad Boys: Ride or Die
[240/998] Bad Boyz (film)
Checkpoint pause for 8.8s...
[241/998] Bad Faith (film)
[242/998] Bad Fish
[243/998] Bad Genius (2024 film)
[244/998] Bad Hair Day (2024 film)
[245/998] Bad Newz (film)
[246/998] Bad Shabbos
[247/998] The Art of Nothing
[248/998] The Assessment

,id,title,wikidata_uri,summary,page_url
0,Q130295240,Ajab Raat Ni Gajab Vaat,http://www.wikidata.org/entity/Q130295240,Ajab Raat Ni Gajab Vaat is a 2024 Gujarati com...,https://en.wikipedia.org/wiki/Ajab_Raat_Ni_Gaj...
1,Q130245494,Alanaati Ramchandrudu,http://www.wikidata.org/entity/Q130245494,Alanaati Ramchandrudu is a 2024 Indian Telugu-...,https://en.wikipedia.org/wiki/Alanaati_Ramchan...
2,Q135901978,Angammal,http://www.wikidata.org/entity/Q135901978,Angammal is a 2025 Indian Tamil-language drama...,https://en.wikipedia.org/wiki/Angammal
3,Q123185887,Anora,http://www.wikidata.org/entity/Q123185887,Anora is a 2024 American romantic comedy-drama...,https://en.wikipedia.org/wiki/Anora
4,Q124532587,Anweshippin Kandethum,http://www.wikidata.org/entity/Q124532587,Anweshippin Kandethum is a 2024 Indian Malayal...,https://en.wikipedia.org/wiki/Anweshippin_Kand...

In [5]:
# Cell 5 — Save crawled data to disk

os.makedirs("data/raw", exist_ok=True)

films_path = "data/raw/wikidata_films.json"
plots_path = "data/raw/wiki_plots.jsonl"
missing_path = "data/raw/wiki_missing_summaries.csv"

with open(films_path, "w", encoding="utf-8") as f:
    json.dump(films, f, indent=2, ensure_ascii=False)

with open(plots_path, "w", encoding="utf-8") as f:
    for rec in plots:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

if "missing_df" in globals() and not missing_df.empty:
    missing_df.to_csv(missing_path, index=False)

print(f"Saved films to: {films_path}")
print(f"Saved plot summaries to: {plots_path}")
if "missing_df" in globals() and not missing_df.empty:
    print(f"Saved missing-summary log to: {missing_path}")

films_df = pd.DataFrame(films)
plots_df = pd.DataFrame(plots)

print("\nFilms preview:")
display(films_df.head())

print("\nPlots preview:")
display(plots_df.head())

Saved films to: data/raw/wikidata_films.json
Saved plot summaries to: data/raw/wiki_plots.jsonl
Saved missing-summary log to: data/raw/wiki_missing_summaries.csv

Films preview:

,uri,id,label,wikipedia_title,date,directors,genres,countries,imdb_ids,cast,awards,production_companies,followed_by,preceded_by
0,http://www.wikidata.org/entity/Q138793787,Q138793787,"1+1+1 Life, Love, Chaos","1+1+1 Life, Love, Chaos",None,[],[],[],[],[],[],[],[],[]
1,http://www.wikidata.org/entity/Q134083298,Q134083298,1-800-On-Her-Own,1-800-On-Her-Own,None,[Dana Flor],[],[United States],[tt32147765],[],[],[],[],[]
2,http://www.wikidata.org/entity/Q131929176,Q131929176,100 Litres of Gold,100 Litres of Gold,None,[Teemu Nikki],[comedy film],"[Denmark, Finland, Italy]",[tt33311744],"[Elina Knihtilä, Elmer Bäck, Jakob Öhrman, Jar...",[],[],[],[]
3,http://www.wikidata.org/entity/Q124414981,Q124414981,105 Minuttess,105 Minuttess,None,[],[],[],[tt15290106],[],[],[],[],[]
4,http://www.wikidata.org/entity/Q125081677,Q125081677,10 Lives,10 Lives,None,"[Chris Jenkins, Mark Koetsier]","[animated film, comedy film]","[Canada, France, United Kingdom, United States]",[tt7959138],[],[],[],[],[]

Plots preview:

,id,title,wikidata_uri,summary,page_url
0,Q130295240,Ajab Raat Ni Gajab Vaat,http://www.wikidata.org/entity/Q130295240,Ajab Raat Ni Gajab Vaat is a 2024 Gujarati com...,https://en.wikipedia.org/wiki/Ajab_Raat_Ni_Gaj...
1,Q130245494,Alanaati Ramchandrudu,http://www.wikidata.org/entity/Q130245494,Alanaati Ramchandrudu is a 2024 Indian Telugu-...,https://en.wikipedia.org/wiki/Alanaati_Ramchan...
2,Q135901978,Angammal,http://www.wikidata.org/entity/Q135901978,Angammal is a 2025 Indian Tamil-language drama...,https://en.wikipedia.org/wiki/Angammal
3,Q123185887,Anora,http://www.wikidata.org/entity/Q123185887,Anora is a 2024 American romantic comedy-drama...,https://en.wikipedia.org/wiki/Anora
4,Q124532587,Anweshippin Kandethum,http://www.wikidata.org/entity/Q124532587,Anweshippin Kandethum is a 2024 Indian Malayal...,https://en.wikipedia.org/wiki/Anweshippin_Kand...

In [6]:
# Cell 6 — Quick crawl statistics and quality checks

num_films = len(films_df)
num_plots = len(plots_df)
num_missing = len(missing_df) if "missing_df" in globals() else 0

avg_summary_len = (
    plots_df["summary"].str.split().str.len().mean()
    if not plots_df.empty else 0
)

print("=== Crawl Summary ===")
print(f"Films retrieved: {num_films}")
print(f"Plot summaries retrieved: {num_plots}")
print(f"Missing summaries: {num_missing}")
print(f"Average summary length (words): {avg_summary_len:.1f}")

print("\n=== Structured metadata coverage ===")
for col in [
    "directors", "genres", "countries", "imdb_ids",
    "cast", "awards", "production_companies",
    "followed_by", "preceded_by"
]:
    if col in films_df.columns:
        non_empty = films_df[col].apply(
            lambda x: len(x) if isinstance(x, list) else 0
        ).gt(0).sum()
        print(f"{col}: {non_empty}/{num_films} films populated")

print("\n=== Example enriched film record ===")
display(films_df.head(1))

print("\n=== Example summary record ===")
display(plots_df.head(1))

=== Crawl Summary ===
Films retrieved: 998
Plot summaries retrieved: 649
Missing summaries: 349
Average summary length (words): 52.6

=== Structured metadata coverage ===
directors: 627/998 films populated
genres: 484/998 films populated
countries: 767/998 films populated
imdb_ids: 952/998 films populated
cast: 477/998 films populated
awards: 28/998 films populated
production_companies: 156/998 films populated
followed_by: 10/998 films populated
preceded_by: 21/998 films populated

=== Example enriched film record ===

,uri,id,label,wikipedia_title,date,directors,genres,countries,imdb_ids,cast,awards,production_companies,followed_by,preceded_by
0,http://www.wikidata.org/entity/Q138793787,Q138793787,"1+1+1 Life, Love, Chaos","1+1+1 Life, Love, Chaos",None,[],[],[],[],[],[],[],[],[]

=== Example summary record ===

,id,title,wikidata_uri,summary,page_url
0,Q130295240,Ajab Raat Ni Gajab Vaat,http://www.wikidata.org/entity/Q130295240,Ajab Raat Ni Gajab Vaat is a 2024 Gujarati com...,https://en.wikipedia.org/wiki/Ajab_Raat_Ni_Gaj...

## Notebook 1 summary

This notebook covered the **data acquisition and cleaning** stage of the project. Its goal was to build an initial movie-centered corpus that could later support information extraction, RDF construction, alignment, reasoning, embedding, and graph-grounded question answering.

### What was done

The notebook first defined the project domain and collected a large list of candidate films from **Wikidata**. For each selected film, basic structured metadata such as identifiers, labels, and Wikipedia-related references were gathered as seed data for the rest of the pipeline.

The second step focused on **Wikipedia summary collection**. Using the available Wikipedia titles, the notebook queried the Wikipedia API and retrieved short plot or descriptive summaries whenever a page was available. Missing pages and failed requests were tracked separately so that coverage issues remained visible instead of being silently ignored.

A cleaning step was then applied to keep only useful textual content for downstream processing. This follows the lab objective of extracting meaningful content rather than raw page boilerplate, and of storing cleaned outputs in reusable machine-readable files. :contentReference[oaicite:0]{index=0}

### Main outputs

This notebook produced the following main artifacts:
- `wikidata_films.json`
- `wiki_plots.jsonl`
- `wiki_missing_summaries.csv`
- `cleaned_plots.jsonl`

### Main findings

The notebook successfully created the initial textual and metadata foundation for the project.  
In practice, this means:
- the project obtained a structured list of movie entities from Wikidata,
- a substantial subset of those movies was enriched with Wikipedia summaries,
- and missing or unresolved pages were explicitly logged for later analysis.

This step is important because later notebooks depend heavily on the quality of this initial corpus. If summaries are noisy, sparse, or missing, then entity extraction, relation extraction, RDF construction, and downstream graph quality will also be affected.

### Why this matters

According to the lab workflow, the first stage of the project should focus on **web crawling / API acquisition**, **clean text collection**, and preparation for later **entity and relation extraction**. The grading guide also expects this part of the project to clearly cover the domain, acquisition strategy, crawler design/ethics, and cleaning pipeline.

This notebook hope to satisfy that role by creating the raw but cleaned dataset that all later notebooks build on.

### Limitations

This stage still has some limitations:
- not every Wikidata film had a usable Wikipedia summary,
- API rate limits and missing pages reduced coverage,
- and Wikipedia summaries are short descriptions rather than full articles, which limits the amount of extractable relational context.

These limitations should be kept in mind when interpreting later extraction and graph-construction results.

### Next step

The next notebook focuses on **information extraction** from the cleaned movie summaries. It uses the collected text to identify entities and candidate relations, which are then transformed into structured knowledge in the following stages of the project.